import nodemailer from 'nodemailer';
import fs from 'fs';
import path from 'path';
import { GeneratedImage } from '../agents/imageGenerationAgent';
import { CopyBundle } from '../agents/copywritingAgent';
import { StrategyDecision } from '../agents/contentStrategyAgent';
import { QAReport } from '../agents/visionQAAgent';

const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: process.env.GMAIL_ADDRESS,
    pass: process.env.GMAIL_APP_PASSWORD, // NOT your regular Gmail password
  },
});

export async function emailPostToPhone(input: {
  images: GeneratedImage[],
  copy: CopyBundle,
  strategy: StrategyDecision,
  qaReport: QAReport,
}) {
  const { images, copy, strategy, qaReport } = input;
  const today = new Date().toLocaleDateString('en-CA');

  console.log(`[EmailDelivery] 📧 Sending post to your phone via email...`);

  // Build image attachments
  const attachments = images.map((img, i) => ({
    filename: `TheStatsAndStacks_Slide_${i + 1}.png`,
    path: img.localPath,
    cid: `slide${i + 1}`, // For embedding in HTML
  }));

  // Build a beautiful HTML email
  const htmlBody = `
  <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; background: #0F172A; color: #E2E8F0; padding: 24px; border-radius: 12px;">
    
    <div style="text-align: center; padding: 16px 0; border-bottom: 1px solid #1E293B;">
      <h1 style="color: #10B981; font-size: 18px; margin: 0;">The<span style="color: #10B981;">Stats</span>And<span style="color: #D4A843;">Stacks</span></h1>
      <p style="color: #64748B; font-size: 11px; margin-top: 4px;">Daily Post — ${today}</p>
    </div>

    <div style="padding: 20px 0;">
      <p style="color: #94A3B8; font-size: 11px; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 4px;">📌 Topic</p>
      <p style="color: white; font-size: 16px; font-weight: bold; margin: 0;">${strategy.topic}</p>
      <p style="color: #64748B; font-size: 12px; margin-top: 4px;">${strategy.format} • ${strategy.slideCount} slides • QA Score: ${(qaReport.overallScore * 100).toFixed(0)}%</p>
    </div>

    <div style="background: #1E293B; border-radius: 8px; padding: 16px; margin-bottom: 16px;">
      <p style="color: #94A3B8; font-size: 11px; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 8px;">📝 CAPTION — Copy this into Instagram:</p>
      <p style="color: #E2E8F0; font-size: 13px; white-space: pre-wrap; line-height: 1.6; margin: 0;">${copy.caption}</p>
    </div>

    <div style="background: #1E293B; border-radius: 8px; padding: 16px; margin-bottom: 16px;">
      <p style="color: #94A3B8; font-size: 11px; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 8px;"># HASHTAGS — Copy this:</p>
      <p style="color: #10B981; font-size: 12px; margin: 0; word-break: break-word;">${copy.hashtags}</p>
    </div>

    <div style="background: #1E293B; border-radius: 8px; padding: 16px; margin-bottom: 16px;">
      <p style="color: #94A3B8; font-size: 11px; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 8px;">💬 FIRST COMMENT — Post this right after publishing:</p>
      <p style="color: #E2E8F0; font-size: 13px; margin: 0;">${copy.firstComment}</p>
    </div>

    <div style="padding: 16px 0;">
      <p style="color: #94A3B8; font-size: 11px; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 12px;">🖼️ YOUR SLIDES — Save these images to your phone:</p>
      ${images.map((img, i) => `
        <div style="margin-bottom: 8px;">
          <img src="cid:slide${i + 1}" style="width: 100%; max-width: 400px; border-radius: 8px; border: 1px solid #334155;" />
          <p style="color: #64748B; font-size: 10px; margin-top: 2px;">Slide ${i + 1}</p>
        </div>
      `).join('')}
    </div>

    <div style="text-align: center; padding: 16px 0; border-top: 1px solid #1E293B;">
      <p style="color: #475569; font-size: 10px; margin: 0;">Generated by your autonomous agent system</p>
    </div>
  </div>
  `;

  // Plain text version
  const textBody = `
═══════════════════════════════════════
THESTATSANDSTACKS — DAILY POST
${today}
═══════════════════════════════════════

📌 TOPIC: ${strategy.topic}
📐 FORMAT: ${strategy.format} (${strategy.slideCount} slides)
📊 QA SCORE: ${(qaReport.overallScore * 100).toFixed(0)}%

───────────────────────────────────────
📝 CAPTION (Copy into Instagram):
───────────────────────────────────────

${copy.caption}

───────────────────────────────────────
# HASHTAGS (Copy these):
───────────────────────────────────────

${copy.hashtags}

───────────────────────────────────────
💬 FIRST COMMENT (Post after publishing):
───────────────────────────────────────

${copy.firstComment}

───────────────────────────────────────

Images are attached to this email.
Save them to your phone gallery, then post to Instagram.
  `;

  await transporter.sendMail({
    from: `"TheStatsAndStacks Bot" <${process.env.GMAIL_ADDRESS}>`,
    to: process.env.DELIVERY_EMAIL, // Where to receive the post
    subject: `📱 IG Post Ready: ${strategy.topic}`,
    text: textBody,
    html: htmlBody,
    attachments,
  });

  console.log(`[EmailDelivery] ✅ Email sent to ${process.env.DELIVERY_EMAIL}`);
}
